spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: foobared
    timeout: 10s
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
        shutdown-timeout: 100ms
  messages:
    basename: i18n/performance-mgt
    encoding: UTF-8
server:
  port: 3344